# Exercise #3: Array calculations and operations

### Use NumPy arrays in mathematical calculations

### Issue covered:



*   Mathematical operations with arrays.
*   Mathematical operations mixing scalars and arrays.
*   Comparisons operators and Boolean operations on arrays.
*   Using the "where" method.
*   Mathematical operations on vectors.
*   Find coefficients and roots of polynomial.



First, import NumPy as np:







In [1]:
import numpy as np



### 1.  Let’s perform some array calculations.





> (a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a":








In [2]:
# Your Code Here#
a = np.array([range(4), range(10,14)])

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


> (b) Create a 1-D array with the vailues [2, -1, 1, 0] and assign it to the variable "b" :


In [3]:
# Your Code Here#
b = np.array([2, -1, 1, 0])

print(b)

[ 2 -1  1  0]



> (c) Multiply array "a" by "b" and view the results:




In [4]:
# Your Code Here#
print(a * b)


[[  0  -1   2   0]
 [ 20 -11  12   0]]


**Do you understand how NumPy has used its broadcasting feature to do the calculation even though the arrays are different shapes?**


It multiplied the vector 'b' by each dimention of matrix 'a' using the dot product:


[ 2 -1  1  0]*[ 0  1  2  3] = [0  -1  2  0]

[ 2 -1  1  0] * [10 11 12 13] = [ 20 -11  12   0]



> (d) Multiply array "b" by 100 and assign the result to the variable "b1":



In [5]:
# Your Code Here#
b1 = b * 100

print(b1)

[ 200 -100  100    0]




> (e) Multiply array "b" by 100.0 and assign the result to the variable "b2":



In [6]:
# Your Code Here#
b2 = b * 100.0

print(b2)

[ 200. -100.  100.    0.]




>(f) Print b1 == b2:





In [7]:
# Your Code Here#
print(b1 == b2)

[ True  True  True  True]


**Are they the same?**

yes




>(g) Why do they display differently? Interrogate the typecode of each array to find out why:



In [8]:
# Your Code Here#
print(b1.dtype, b2.dtype)

int32 float64


###2. Let's perform some operations on array.





> (a) Continue to use arrays "a" defined above:




In [9]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]




> (b) Print the sum, mean and the product of "a" in two different ways:




In [10]:
# Your Code Here#
print(a.sum(), a.mean(), a.prod())

print(np.sum(a), np.mean(a), np.prod(a))

52 6.5 0
52 6.5 0




>(c) Print the variance and the standard deviation of "a"in two different ways:




In [11]:
# Your Code Here#
print(a.var(), a.std())
print(np.var(a), np.std(a))

26.25 5.123475382979799
26.25 5.123475382979799


###3. Let’s look at array comparisons.





>(a)  Create an array of values 0 to 9 and assign it to the variable "arr":




In [12]:
# Your Code Here#
arr = np.array(range(10))

print(arr)

[0 1 2 3 4 5 6 7 8 9]




>(b)  Print two different ways of expressing the condition where the array is less than 3:




In [13]:
# Your Code Here#
print(arr < 3)
print(np.less(arr, 3))

[ True  True  True False False False False False False False]
[ True  True  True False False False False False False False]




>(c)  Create a numpy condition where "arr" is less than 3 OR greater than 8:




In [14]:
# Your Code Here#
condition = np.logical_or(arr < 3, arr > 8)
print(condition)

[ True  True  True False False False False False False  True]




>(d)  Use the  *where*  function to create a new array where the value is arr * 5 if the above condition is True and arr * -5 where the condition is False:




In [15]:
# Your Code Here#
new_arr = np.where(condition, arr * 5, arr * -5)
print(new_arr)

[  0   5  10 -15 -20 -25 -30 -35 -40  45]


###4. Let’s look at item selection and manipulation.





>(a)  Continue to use arrays "a" defined above:




In [16]:
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]




>(b)  Print an array contains all the values from "a" that are greater than 1:




In [17]:
# Your Code Here#
print(a[a > 1])

[ 2  3 10 11 12 13]




>(c)  Print an array contains all the values from "a" that are greater than 3 and smaller than 11:




In [18]:
# Your Code Here#
print(a[np.logical_and(a > 3, a < 11)])

[10]




>(d)  Create an array from the list range(6) and assign it to the variable "b":



In [19]:
# Your Code Here#
b = np.array(range(6))
print(b)

[0 1 2 3 4 5]




>(e)  Use the  *put*  function to replace the first element of "b" with 6:




In [20]:
# Your Code Here#
b.put([0], 6)
print(b)

[6 1 2 3 4 5]




>(f)  Create an array from the list range(5) and assign it to the variable "c":




In [21]:
# Your Code Here#
c = np.array(range(5))
print(c)

[0 1 2 3 4]




>(g)   Use the  *put*  function to replace the first element of "b" with the last element of "c":



In [22]:
# Your Code Here#
b.put([-1], c)
print(b)

[6 1 2 3 4 0]
