![image.png](attachment:image.png)

![image.png](attachment:image.png)

In [ ]:
import numpy as np
from autograd import grad, jacobian

In [ ]:
A = np.array([[3,1,1],
              [1,2,0],
              [0,0,1]])


b = np.array([[2,1,3]]).T

In [ ]:
U = np.triu(A)
L = np.tril(A)
D = np.diag(np.diag(A))
U,D,L

(array([[3, 1, 1],
        [0, 2, 0],
        [0, 0, 1]]),
 array([[3, 0, 0],
        [0, 2, 0],
        [0, 0, 1]]),
 array([[3, 0, 0],
        [1, 2, 0],
        [0, 0, 1]]))

In [ ]:
x = np.array([0,0,0], dtype=float)
for i in range(10):
    x = np.linalg.inv(D)*(b-(L+D)*x)

x


array([[ -227.33333333,     0.        ,     0.        ],
       [    0.        ,  -170.5       ,     0.        ],
       [    0.        ,     0.        , -1023.        ]])

In [ ]:
x = np.linalg.inv(D)*(b-(L+D)*x)