In [1]:
import pandas as pd
import numpy as np

In [2]:
from scipy.stats import skew, mode
from scipy.stats import norm, kurtosis
import matplotlib.pyplot as plt

In [3]:
a = np.array([1,2,1,10,5,10,4])

In [4]:
a

array([ 1,  2,  1, 10,  5, 10,  4])

In [5]:
b = np.array([1,2,1,10,5,10,4,100,-3])
c = np.array([1,2,1,10,10,5,10,4,100,-3])

Skewness regular

In [6]:
skewa = skew(a)
skewb = skew(b)
skewa, pd.Series(a).skew(), skewb, pd.Series(b).skew()

(0.5221463933410836, 0.6767790763704878, 2.3940838777223306, 2.902067905143163)

Skewness Pearson

In [7]:
mean = b.mean()
med = np.median(b)
std = b.std()
pearson = (mean - med) / std
pearson, skew(b,bias=False)

(0.34231872919076783, 2.9020679051431633)

In [8]:
mean = a.mean()
med = np.median(a)
std = a.std()
pearson = (mean - med) / std
pearson, skew(a,bias=False)

(0.19764235376052372, 0.6767790763704881)

Kurtosis

In [9]:
kura = kurtosis(a, fisher=False)
kurb = kurtosis(b)
kurc = kurtosis(c)
kura,kurb,kurc

(1.6717480468749997, 3.8955747699219705, 4.785122954940543)

In [10]:
pd.Series(a).kurtosis(),pd.Series(b).kurtosis(),pd.Series(c).kurtosis()

(-1.3878046875, 8.562999561756133, 9.423699509627031)

Mode

In [11]:
moda = mode(a)
modb = mode(b)
modc = mode(c)
moda,modb,modc

(ModeResult(mode=array([1]), count=array([2])),
 ModeResult(mode=array([1]), count=array([2])),
 ModeResult(mode=array([10]), count=array([3])))

# a normalized

In [12]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import gamma

## a min-max normalization

In [13]:
(a - np.min(a))/(np.max(a)- np.min(a))

array([0.        , 0.11111111, 0.        , 1.        , 0.44444444,
       1.        , 0.33333333])

## a Z transform- average is 0 and std is 1

In [14]:
(a - a.mean())/(a.std())

array([-1.02774024, -0.75104094, -1.02774024,  1.46255342,  0.07905694,
        1.46255342, -0.19764235])

# a unit length normalization
Normalizing an array will return the normal form of the array, which has a vector magnitude of 1.

In [15]:
#norm(a) = root(a1^2 + + a2^2 + ... + an^2)
norm = np.linalg.norm(a)
normal_a = a/norm
a, norm, normal_a

(array([ 1,  2,  1, 10,  5, 10,  4]),
 15.716233645501712,
 array([0.06362848, 0.12725695, 0.06362848, 0.63628476, 0.31814238,
        0.63628476, 0.25451391]))

# Outliers

### 3 standard division away from the mean

In [51]:
b = np.array([1,2,1,10,15,20,30,7,9,5,10,4,100,-3])
arr = np.random.randint(0,100, 1000)
arr = b
arr.mean(), arr.std()

(15.071428571428571, 24.972740240150674)

In [52]:
outlier1 = [x for x in arr if np.abs(x - np.mean(arr))/np.std(arr) > 3]
outlier1

[100]

### 3 MAD away from the median

In [53]:
mad_arr = np.median([np.abs(x - np.median(arr)) for x in arr])
mad_arr

6.5

In [54]:
outlier2 = [x for x in arr if np.abs(x - np.mean(arr))/mad_arr > 3]
outlier2

[100]

### Quantiles- 2*Q.75 - Q.25 and Q.75 - 2* Q.25

In [55]:
q75 = np.quantile(arr, 0.75)
q25 = np.quantile(arr, 0.25)
q75, q25

(13.75, 2.5)

In [56]:
upper = 2*q75 - q25
lower = q75 - 2 * q25
upper, lower

(25.0, 8.75)

In [47]:
outlier2 = [x for x in arr if x < lower or x > upper]
outlier2

[1, 2, 1, 30, 7, 5, 4, 100, -3]